'use strict';
const fs=require('fs'),assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const main=read('main.js'),pre=read('preload.js'),html=read('src/index.html'),app=read('src/app.js'),i=read('src/integration/666-integration.js'),arch=read('docs/ARCHITECTURE.md');
const pass=(n,c)=>{assert(c,n);console.log('PASS',n)};
pass('Soundwave original canvas retained',html.includes('visualizer-canvas')&&app.includes('drawVisualizer(activeStyle'));
pass('Soundwave local file owner retained',main.includes("dialog:openAudio")&&app.includes('window.api.openAudio()'));
pass('source hub local/radio/soundcloud',html.includes('data-source="local"')&&html.includes('data-source="radio"')&&html.includes('data-source="soundcloud"'));
pass('radio canonical stream and fallback config',read('src/shared/radio-config.cjs').includes("stream:'/stream'")&&read('src/shared/radio-config.cjs').includes("fallbackStream:'/fallback-stream'"));
pass('admin token main-process only',main.includes("let adminToken = ''")&&!pre.includes('adminToken')&&!i.includes('adminToken'));
pass('canonical auth gate',main.includes("gateRoute")&&main.includes('authOk')&&main.includes('pwOk'));
pass('AutoDJ skip adapter',main.includes("radio:skip")&&pre.includes('radioSkip'));
pass('Player Messenger adapter',main.includes("player-alert:send")&&html.includes('player-message'));
pass('Discord adapters',main.includes('discordMessageRoute')&&main.includes('discordNowPlayingRoute'));
pass('CaYatur analyzer donor staged',fs.existsSync('src/vendor/cayatur/analysis.js'));
pass('CaYatur spectrum runtime wired',i.includes('SVSpectrum')&&i.includes('barEngine.compute'));
pass('CaYatur deep analyzer runtime wired',i.includes('SVAnalysis')&&i.includes('analyzer.update'));
pass('MilkDrop runtime promoted',fs.existsSync('src/vendor/cayatur/milkdrop-core.js')&&fs.existsSync('src/vendor/cayatur/milkdrop-renderer.js')&&html.includes('<option value="milkdrop">')&&i.includes("engine==='milkdrop'"));
pass('3D dependency closure present',fs.existsSync('src/vendor/cayatur/geometry3d.js')&&fs.existsSync('src/vendor/cayatur/formulas.js')&&fs.existsSync('src/vendor/cayatur/solids.js'));
pass('3D runtime wired and selectable',html.includes('<option value="geometry3d">')&&i.includes("engine==='geometry3d'")&&i.includes('contextLost'));
pass('local audio no longer base64 duplicated',main.includes('swmedia')&&!main.includes('audioData.toString'));
pass('local output synchronization',i.includes("['radio','local','soundcloud'].includes(st.mode)"));
pass('display hotplug recovery',main.includes("screen.on('display-added'")&&main.includes("screen.on('display-removed'")&&pre.includes('onDisplaysChanged'));
pass('3D scene selector',html.includes('geometry-preset')&&html.includes('surface:klein')&&html.includes('attractor:lorenz'));
pass('maximized adaptive startup',main.includes('mainWindow.maximize()'));
pass('shader runtime promoted',fs.existsSync('src/vendor/cayatur/shaderhost.js')&&html.includes('<option value="shader">')&&i.includes('SVShaderHost')&&i.includes('shaderHost.render'));
pass('shader presets selectable',html.includes('shader-preset')&&html.includes('Neon Plasma')&&html.includes('Cyber Tunnel')&&html.includes('Spectrum Grid'));
pass('renderer security hardening',main.includes('sandbox: true')&&main.includes('webSecurity: true')&&main.includes('setWindowOpenHandler')&&main.includes('setPermissionRequestHandler'));
pass('internal media bridge privileged',main.includes('registerSchemesAsPrivileged')&&main.includes("protocol.handle('swmedia'")&&main.includes('net.fetch'));
pass('CaYatur MIT notice preserved',read('src/vendor/cayatur/LICENSE').includes('MIT License')&&read('src/vendor/cayatur/LICENSE').includes('CaYaDev'));
pass('responsive fullframe CSS',read('src/style.css').includes('body.fullframe')&&read('src/style.css').includes('100vw'));
pass('display discovery',main.includes('screen.getAllDisplays()')&&pre.includes('displays:'));
pass('selectable output windows',main.includes('openOutputWindows')&&html.includes('display-one')&&html.includes('display-two'));
pass('display hot source broadcast',main.includes("source:state")&&pre.includes('onSourceState'));
pass('production mutation absent',!main.includes('git push')&&!main.includes('cloudflare'));
pass('architecture hardlocks documented',arch.includes('SOUNDWAVE CORE')&&arch.includes('Production WebRadio is never mutated'));
pass('controlled milk import',main.includes("dialog:openMilkdrop")&&main.includes('milk_preset_too_large')&&pre.includes('openMilkdrop')&&html.includes('milkdrop-import')&&i.includes('importedMilkdrop'));
pass('SoundCloud credentials isolated in main process',main.includes('SOUNDCLOUD_CLIENT_ID')&&main.includes('SOUNDCLOUD_CLIENT_SECRET')&&!pre.includes('SOUNDCLOUD_CLIENT_SECRET')&&!i.includes('SOUNDCLOUD_CLIENT_SECRET'));
pass('SoundCloud OAuth client credentials main-process flow',main.includes("grant_type:'client_credentials'")&&main.includes('soundCloudAccessToken'));
pass('SoundCloud internal stream protocol',main.includes("scheme:'swsc'")&&main.includes("protocol.handle('swsc'")&&i.includes('swsc://audio/current')===false);
pass('SoundCloud resolver renderer contract',pre.includes('soundCloudResolve')&&i.includes('window.api.soundCloudResolve')&&html.includes('soundcloud-state'));
pass('SoundCloud attribution surface',html.includes('Audio source: SoundCloud')&&html.includes('OPEN ON SOUNDCLOUD')&&main.includes('soundcloud:open-current'));
pass('secondary output supports SoundCloud',i.includes("['radio','local','soundcloud'].includes(st.mode)"));
pass('secondary output clock correction',i.includes('Math.abs(audio.currentTime-st.time)>.35')&&i.includes("audio.addEventListener('timeupdate'"));
pass('SoundCloud setup documented',fs.existsSync('docs/SOUNDCLOUD_SETUP.md'));
pass('visual engine leader follower sync',i.includes('visualState')&&i.includes('st?.visual')&&i.includes('importedMilkdrop=v.importedMilkdrop'));
pass('visual presets sync to outputs',i.includes('shaderPreset')&&i.includes('geometryPreset')&&i.includes('milkdropPreset'));
pass('SoundCloud playlist queue normalized in main process',main.includes('soundCloudQueue = []')&&main.includes('activateSoundCloudIndex')&&main.includes('soundcloud:next')&&main.includes('soundcloud:previous'));
pass('SoundCloud queue controls exposed safely',pre.includes('soundCloudNext')&&pre.includes('soundCloudPrevious')&&html.includes('soundcloud-prev')&&html.includes('soundcloud-next'));
pass('SoundCloud automatic queue advance',i.includes("audio.addEventListener('ended'")&&i.includes('window.api.soundCloudNext()'));
pass('SoundCloud stream protocol route constrained',main.includes("u.hostname!=='audio'||u.pathname!=='/current'"));
pass('SoundCloud media URL revision busts stale stream',main.includes('soundCloudRevision++')&&main.includes('swsc://audio/current?v='));
pass('display metrics reconcile active output bounds',main.includes('reconcileOutputWindows')&&main.includes('w.setBounds')&&main.includes('display-metrics-changed'));
pass('display output status IPC',main.includes("display:status")&&pre.includes('outputStatus'));
pass('display selections persist across discovery refresh',i.includes("s666-display-one")&&i.includes("s666-display-two"));
pass('additive visual engines fail soft to Soundwave core',app.includes('fail-soft fallback')&&app.includes('extensionHandled = false'));
pass('HiDPI and 4K CSS hardening present',read('src/style.css').includes('min-resolution:1.5dppx')&&read('src/style.css').includes('min-width:2560px'));
pass('secondary output heartbeat IPC',main.includes("display:heartbeat")&&pre.includes('outputHeartbeat')&&i.includes('window.api.outputHeartbeat'));
pass('secondary output crash recovery',main.includes('render-process-gone')&&main.includes('outputRecovery')&&main.includes('w.reload()'));
pass('secondary output unresponsive state tracking',main.includes("webContents.on('unresponsive'")&&main.includes("engine:'unresponsive'"));
pass('runtime GPU diagnostics exposed safely',main.includes('runtime:diagnostics')&&main.includes('getGPUFeatureStatus')&&pre.includes('runtimeDiagnostics'));
pass('output health status includes fps and recovery count',main.includes('responsive:')&&main.includes('recoveries:')&&main.includes('lastHeartbeat'));
pass('release integrity command wired',read('package.json').includes('check:release')&&read('package.json').includes('release-integrity.cjs'));
pass('portable build is release-gated',read('BUILD_SOUNDWAVE_666_PORTABLE.bat').includes('npm run check:release'));
pass('Chromium license notice is not deleted by packager',!read('scripts/build.js').includes("fs.unlinkSync(licenseHtml)"));
pass('syntax checker covers application tree',read('scripts/check-syntax.cjs').includes("'main.js','preload.js','src','scripts','tests'"));
pass('release scan excludes audit self-literals but scans shipped runtime',read('scripts/release-integrity.cjs').includes("['main.js','preload.js','src','docs']"));
pass('runtime diagnostics export is main-process owned',main.includes('runtime:export-diagnostics')&&pre.includes('exportRuntimeDiagnostics')&&html.includes('export-diagnostics'));
pass('runtime diagnostics include physical display scale data',main.includes('scaleFactor:d.scaleFactor')&&main.includes('workArea:d.workArea'));
pass('packager preserves Electron locales',read('scripts/build.js').includes('Locale integrity gate failed')&&!read('scripts/build.js').includes("file !== 'en-US.pak'"));
pass('packager requires Chromium legal notice',read('scripts/build.js').includes('Chromium third-party license notice missing'));
pass('packager emits SHA256 artifact manifest',read('scripts/build.js').includes('RELEASE_ARTIFACT_SHA256SUMS.txt')&&read('scripts/build.js').includes("createHash('sha256')"));
pass('IPC sender validation wraps privileged channels',main.includes('function registerIpc(channel, roles, handler)')&&main.includes("throw new Error('ipc_sender_blocked')"));
pass('secondary outputs are restricted to heartbeat IPC',main.includes("registerIpc('display:heartbeat','output'")&&main.includes("registerIpc('auth:login','main'")&&main.includes("registerIpc('file:startWrite','main'"));
pass('video export write path requires dialog approval',main.includes('approvedSavePath')&&main.includes("throw new Error('save_path_not_approved')"));
pass('video export IPC chunks are bounded',main.includes('8 * 1024 * 1024')&&main.includes('write_chunk_too_large'));
pass('navigation is constrained to Soundwave index document',main.includes('function trustedAppUrl')&&main.includes("u.protocol === 'file:'")&&main.includes('u.pathname === expected.pathname'));
pass('renderer CSP blocks object and frame embedding',html.includes('Content-Security-Policy')&&html.includes("object-src 'none'")&&html.includes("frame-src 'none'")&&!html.includes('fonts.googleapis.com'));
pass('radio fallback is runtime-active',i.includes('RADIO FAILOVER · FALLBACK ACTIVE')&&i.includes('radioCfg.fallback')&&i.includes("audio.addEventListener('error'"));
pass('radio failover is bounded against loops',i.includes('radioFailoverBusy')&&i.includes('radioUsingFallback'));
pass('nowplaying polling adapts to visibility',i.includes('document.hidden?30000:10000')&&i.includes("document.addEventListener('visibilitychange'"));
pass('radio fallback schedules bounded main recovery',i.includes('scheduleRadioRecovery')&&i.includes('probeRadioMain')&&i.includes('setTimeout(()=>finish(false),10000'));
pass('radio recovery preserves fallback until main probe succeeds',i.includes('if(await probeRadioMain())')&&i.includes('RADIO RECOVERY · MAIN RESTORED')&&i.includes('RADIO RECOVERY · FALLBACK STABLE'));
pass('network online accelerates radio main recovery',i.includes("window.addEventListener('online'")&&i.includes('scheduleRadioRecovery(1500)'));
pass('source state IPC payload is schema constrained',main.includes('function sanitizeSourceState')&&main.includes('source_protocol_blocked')&&main.includes('visual_preset_too_large'));
pass('output recovery budget resets after successful load',main.includes("did-finish-load',()=>{outputRecovery.set(id,0)"));
pass('runtime diagnostics include process memory',main.includes('process.memoryUsage()')&&main.includes('heapUsed:m.heapUsed'));
pass('SoundCloud API requests are timeout bounded',main.includes('async function soundCloudFetch')&&main.includes("soundcloud_timeout")&&main.includes('15000'));
pass('SoundCloud OAuth invalidation retries once',main.includes('if(r.status===401){soundCloudToken=null')&&main.includes('const retry=await soundCloudAccessToken()'));
pass('SoundCloud renderer recovery skips bounded failures',i.includes('soundCloudErrorSkips>=3')&&i.includes('skipping ${soundCloudErrorSkips}/3'));
pass('offline network state is surfaced to active remote sources',i.includes("window.addEventListener('offline'")&&i.includes('Network offline'));
pass('single-instance runtime lock prevents duplicate controllers',main.includes('requestSingleInstanceLock')&&main.includes("second-instance"));
pass('Windows suspend resume lifecycle is surfaced',main.includes("powerMonitor.on('suspend'")&&main.includes("powerMonitor.on('resume'")&&pre.includes('onRuntimeLifecycle')&&i.includes('SYSTEM RESUME · REHYDRATING'));
pass('stale output heartbeat has bounded watchdog recovery',main.includes('startOutputWatchdog')&&main.includes('output-heartbeat-timeout')&&main.includes('attempts>=3'));
pass('runtime diagnostics retain bounded lifecycle event history',main.includes('runtimeEvents.length>200')&&main.includes('events:runtimeEvents.slice(-100)'));
pass('background imports are size and type bounded',main.includes('background_too_large')&&main.includes('32*1024*1024')&&main.includes('background_type_blocked'));
pass('local media bridge has no duplicate unreachable fetch', (main.match(/return net\.fetch\(pathToFileURL\(selectedLocalAudioPath\)/g)||[]).length===1);
pass('quit path clears transient credentials and writers',main.includes("app.on('before-quit'")&&main.includes("adminToken=''; soundCloudToken=null")&&main.includes('fileWriteStream.end()'));
pass('Player Messenger receive polling and self suppression',i.includes('refreshPlayerMessenger')&&i.includes('from!==senderId')&&i.includes('document.hidden?30000:10000'));
pass('Player Messenger history and status adapters stay main-process owned',main.includes("player-alert:history")&&main.includes("player-alert:status")&&pre.includes('playerAlertHistory')&&pre.includes('playerAlertStatus'));
pass('Discord automatic track change is deduplicated after authenticated enable',i.includes('discordAutoEnabled=true')&&i.includes('key!==lastDiscordTrack')&&i.includes('discordNowPlaying(metadata())'));
pass('SoundCloud consecutive failure counter resets on confirmed playing',i.includes("audio.addEventListener('playing'")&&!i.includes('const playSoundCloud=async x=>{soundCloudErrorSkips=0'));
pass('radio fallback failure enters degraded recovery state',i.includes('RADIO DEGRADED · MAIN + FALLBACK UNAVAILABLE')&&i.includes('radioFallbackFailed=true'));
pass('radio recovery cadence is jittered and fallback retry accelerated',i.includes('45000+Math.floor(Math.random()*30001)')&&i.includes('scheduleRadioRecovery(5000)'));
const py=read('soundwave_666.py');
pass('Python host preserves Soundwave runtime ownership',py.includes('Soundwave Studio remains UI/playback owner')&&py.includes('["npm", "start"]'));
pass('Python host exposes integrity and portable build controls',py.includes('["npm", "run", "check:release"]')&&py.includes('["npm", "run", "package"]'));
pass('Python host preflight checks Node npm and package metadata',py.includes('shutil.which')&&py.includes('package.json')&&py.includes('PREFLIGHT · BLOCKED'));
pass('Python host SoundCloud credentials are RAM-only environment handoff',py.includes('SOUNDCLOUD_CLIENT_ID')&&py.includes('SOUNDCLOUD_CLIENT_SECRET')&&py.includes('never saved')&&!py.includes('write_text('));
pass('Python host marshals background UI updates onto Tk event loop',py.includes('self.after(0, fn, *args)')&&py.includes('self.ui(self.set_status'));
pass('Python host prevents concurrent maintenance tasks',py.includes('self.busy')&&py.includes('another maintenance task is running'));
pass('Python host stops Windows Electron process tree',py.includes('taskkill')&&py.includes('/T')&&py.includes('/F'));
pass('Python host EXE builder is explicit and non-installing',read('BUILD_PYTHON_HOST_EXE.bat').includes('PYINSTALLER_NOT_FOUND')&&read('BUILD_PYTHON_HOST_EXE.bat').includes('No package is installed automatically'));
pass('Python host dependency install is explicit user action',py.includes('INSTALL DEPS')&&py.includes('["npm", "install"]')&&py.includes('only when you explicitly click it'));
pass('Python host start and build require Electron dependencies',py.includes('dependencies_ready()')&&py.includes('node_modules')&&py.includes('electron-packager'));

pass('MASTER Soundwave stage has additive radio composition',html.includes('source-artwork-bg')&&html.includes('radio-visual-header')&&html.includes('source-nowplaying-ticker')&&i.includes("composeStage('radio'"));
pass('radio visual metadata survives source state hardening',main.includes("['name','artist','dj','permalink','artwork']")&&i.includes('composeStage(st.mode,st)'));
pass('SoundCloud creator library is pinned to Fraggelpower666',main.includes('https://soundcloud.com/fraggelpower666')&&main.includes('soundCloudCreatorLibrary')&&pre.includes('soundCloudLibrary'));
pass('SoundCloud library exposes playlists and tracks in Soundwave UI',html.includes('soundcloud-library')&&i.includes("section('PLAYLISTS / ALBUMS'")&&i.includes("section('TRACKS'"));
pass('SoundCloud prefers URN track identity',main.includes('track.urn')&&main.includes('soundCloudCurrent.urn||soundCloudCurrent.id'));
pass('SoundCloud refresh token is reused',main.includes("grant_type:'refresh_token'")&&main.includes('soundCloudToken?.refreshToken'));
const masterLock=read('MASTER_UI_LOCK_v1.18.md');
pass('master UI lock documents source composition',masterLock.includes('Soundwave Studio original 11 MB lineage')&&masterLock.includes('stream artwork background')&&masterLock.includes('playlists/albums/sets'));
console.log('116/116 DEEP INTEGRATION STATIC GATES PASS');
