import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const js=read('js/main-veluna-adapter.js');
const css=read('css/main-veluna-adapter.css');
const desktopCss=read('css/desktop.css');
const stageCss=read('css/player-stage-v2.css');
const patchesCss=read('css/player-patches.css');
const indexHtml=read('index.html');
const centralBoot=read('js/central-boot-screen.js');
const headers=read('_headers');
const bootstrap=read('config/veluna-assets.js');

test('main VELUNA adapter root/public mirrors are byte-identical',()=>{
  assert.equal(read('public/js/main-veluna-adapter.js'),js);
  assert.equal(read('public/css/main-veluna-adapter.css'),css);
  assert.equal(read('public/_headers'),headers);
});
test('bootstrap config is revalidated and loads one main adapter',()=>{
  assert.match(headers,/\/config\/\*\n  Cache-Control: no-cache, must-revalidate/);
  assert.match(bootstrap,/mainVelunaAdapterVersion = '2026-08-23-main-ticker-dynamic-lane-dna-contained-v4'/);
  assert.match(bootstrap,/main-veluna-adapter\.css/);
  assert.match(bootstrap,/main-veluna-adapter\.js/);
});
test('main ticker keeps fitting titles whole and only scrolls genuinely long titles',()=>{
  assert.match(js,/const TICKER_STATIC_PADDING=24/);
  assert.match(js,/const itemWidth=measureTextWidth\(ticker\)/);
  assert.match(js,/if\(itemWidth<=Math\.max\(0,laneWidth-TICKER_STATIC_PADDING\)\)\{/);
  assert.match(js,/ticker\.classList\.add\('is-static'\)/);
  assert.match(css,/\.is-static\{min-width:100%!important;translate:0 0!important\}/);
});
test('mobile adapter ownership neutralizes legacy full-field marquee for fitting desktop-DOM titles and preserves owned long-title drivers',()=>{
  assert.match(desktopCss,/padding-left:100%!important/);
  assert.match(desktopCss,/MobileTicker[\w-]*[^\n]*infinite!important/);
  assert.match(css,/@media \(max-width:760px\)\{[\s\S]*#nowPlayingTicker\.s666-veluna-main-ticker\{[\s\S]*padding-left:0!important;[\s\S]*transform:none!important;[\s\S]*animation:none!important/);
  assert.match(css,/@media \(max-width:760px\)\{[\s\S]*#nowPlayingTicker\.s666-veluna-main-ticker\.is-static\{[\s\S]*min-width:100%!important;[\s\S]*padding-left:0!important;[\s\S]*animation:none!important;[\s\S]*translate:0 0!important/);
  assert.match(css,/@media \(max-width:760px\)\{[\s\S]*is-running\[data-s666-ticker-driver="css"\][\s\S]*animation:s666VelunaMainTicker var\(--ticker-duration,18s\) linear infinite!important/);
  assert.match(css,/@media \(max-width:760px\)\{[\s\S]*is-running\[data-s666-ticker-driver="waapi"\][\s\S]*animation:none!important/);
});
test('actual rendered <=760px MFF title is discovered, classified and overrides legacy unconditional marquees',()=>{
  assert.match(indexHtml,/id='mffApp'/);
  assert.match(indexHtml,/class="mff-title"><small>NOW PLAYING<\/small><h1><span>666SOUNDsDESIGn WebRadio<\/span><\/h1>/);
  assert.match(indexHtml,/\.player-shell/);
  assert.match(indexHtml,/try\{n\.remove\(\)\}catch\(e\)\{\}/);
  assert.match(stageCss,/#mffApp \.mff-title h1 \.s666-title-marquee\{[\s\S]*animation:s666TitleMarquee 15s linear infinite!important/);
  assert.match(patchesCss,/\.mff-title h1 span\{[\s\S]*padding-left:100%!important;[\s\S]*animation:mffMarquee 13s linear infinite!important/);
  assert.match(js,/function syncMffTickerMotion\(\)/);
  assert.match(js,/if\(window\.innerWidth>760\) return/);
  assert.match(js,/#mffApp \.mff-title h1/);
  assert.match(js,/ticker\.classList\.add\('s666-veluna-mff-ticker'\)/);
  assert.match(js,/ticker\.dataset\.s666MffTickerSignature===signature/);
  assert.match(js,/ticker\.dataset\.s666MffTickerDriver/);
  assert.match(js,/mffTickerAnimation\.id='s666-mff-marquee'/);
  assert.match(js,/function installMffTicker\(\)/);
  assert.match(js,/function discoverMffTicker\(\)/);
  assert.match(js,/mffDiscoveryObserver\.observe\(document\.body,\{childList:true,subtree:true\}\)/);
  assert.match(css,/#mffApp \.mff-title h1 span\.s666-veluna-mff-ticker\{[\s\S]*padding-left:0!important;[\s\S]*transform:none!important;[\s\S]*animation:none!important/);
  assert.match(css,/#mffApp \.mff-title h1 span\.s666-veluna-mff-ticker\.is-static\{[\s\S]*min-width:100%!important;[\s\S]*animation:none!important;[\s\S]*translate:0 0!important/);
  assert.match(css,/s666-veluna-mff-ticker\.is-running\[data-s666-mff-ticker-driver="css"\][\s\S]*animation:s666VelunaMainTicker var\(--ticker-duration,18s\) linear infinite!important/);
  assert.match(css,/s666-veluna-mff-ticker\.is-running\[data-s666-mff-ticker-driver="waapi"\][\s\S]*animation:none!important/);
});
test('long-title ticker measures one complete repeat segment and loops infinitely without seam drift',()=>{
  assert.match(js,/const TICKER_REPEAT_GAP=48/);
  assert.match(js,/function measureLoopSegmentWidth\(ticker,text\)/);
  assert.match(js,/gap\.style\.cssText=`display:inline-block;width:\$\{TICKER_REPEAT_GAP\}px;height:1px;`/);
  assert.match(js,/separator\.textContent=' ◆ '/);
  assert.match(js,/probe\.append\(first,gap,separator,second\)/);
  assert.match(js,/secondRect\.left-firstRect\.left/);
  assert.match(js,/const shift=Math\.max\(1,measureLoopSegmentWidth\(ticker,text\)\)/);
  assert.match(js,/const duration=Math\.max\(12,shift\/42\)/);
  assert.doesNotMatch(js,/Math\.min\(52,shift\/42\)/);
  assert.match(js,/--ticker-segment-width/);
  assert.match(js,/iterations:Infinity/);
  assert.match(js,/ticker\.animate\(/);
  assert.match(js,/tickerAnimation\.id='s666-main-marquee'/);
  assert.match(js,/data-s666-ticker-driver/);
  assert.match(js,/ticker\.classList\.add\('is-running'\)/);
  assert.match(js,/MutationObserver/);
  assert.match(css,/content:" ◆ " attr\(data-s666-marquee-text\)/);
  assert.match(css,/padding-left:48px!important/);
  assert.match(css,/linear infinite!important/);
  assert.match(css,/data-s666-ticker-driver="waapi"/);
  assert.match(css,/data-s666-ticker-driver="css"/);
});
test('main ticker geometry calibrates rendered viewport edges to the real cover and History edges',()=>{
  assert.match(js,/const TICKER_EDGE_INSET=18/);
  assert.match(js,/const TICKER_COVER_GAP=20/);
  assert.match(js,/const TICKER_MIN_WIDTH=96/);
  assert.match(js,/function syncTickerGeometry\(\)/);
  assert.match(js,/const tickerWindow=q\('\.ticker-window',now\|\|document\)/);
  assert.match(js,/desiredLeft=Math\.max\(desiredLeft,rect\.right\+TICKER_COVER_GAP\)/);
  assert.match(js,/desiredRight=Math\.min\(nowRect\.right,Math\.max\(desiredLeft\+TICKER_MIN_WIDTH,rect\.right\)\)/);
  assert.match(js,/const rendered=tickerWindow\.getBoundingClientRect\(\)/);
  assert.match(js,/const leftError=desiredLeft-rendered\.left/);
  assert.match(js,/const rightError=desiredRight-rendered\.right/);
  assert.match(js,/width=Math\.max\(TICKER_MIN_WIDTH,Math\.round\(width\+rightError-leftError\)\)/);
  assert.match(js,/--s666-main-ticker-left/);
  assert.match(js,/--s666-main-ticker-right/);
  assert.match(js,/--s666-main-ticker-right-edge/);
  assert.match(js,/--s666-main-ticker-width/);
  assert.match(js,/\['play','playing','pause','loadedmetadata','durationchange'\]/);
  assert.match(css,/width:var\(--s666-main-ticker-width/);
  assert.match(css,/left:var\(--s666-main-ticker-left,18px\)!important/);
  assert.match(css,/#historyToggle\{position:relative!important;z-index:7!important\}/);
  assert.match(css,/\.ticker-window\{[\s\S]*overflow:hidden!important;[\s\S]*isolation:isolate!important/);
});
test('main ticker geometry continuously resyncs when cover, panel or History dimensions change',()=>{
  assert.match(js,/typeof ResizeObserver==='function'/);
  assert.match(js,/const observer=new ResizeObserver\(scheduleTickerSync\)/);
  assert.match(js,/\[q\('\.now-playing'\),q\('\.now-cover-wrap'\),q\('#historyToggle'\)\]\.filter\(Boolean\)/);
  assert.match(js,/window\.__S666_MAIN_TICKER_RESIZE_OBSERVER__=observer/);
});
test('main ticker is absolutely anchored in the lower third with responsive breathing room',()=>{
  assert.match(css,/position:absolute!important/);
  assert.match(css,/top:auto!important/);
  assert.match(css,/bottom:42px!important/);
  assert.match(css,/@media \(min-width:761px\) and \(max-height:820px\)\{[\s\S]*ticker-window\{bottom:18px!important\}/);
  assert.match(css,/min-height:44px!important/);
  assert.match(css,/height:44px!important/);
  assert.match(css,/margin:0!important/);
  assert.match(css,/align-self:auto!important/);
  assert.match(css,/display:flex!important/);
  assert.match(css,/align-items:center!important/);
  assert.match(css,/line-height:34px!important/);
  assert.doesNotMatch(css,/grid-template-rows:minmax\(0,1fr\) 62px!important/);
  assert.doesNotMatch(css,/bottom:16px!important/);
});
test('unchanged repeated metadata does not restart a long-title marquee before a full cycle',()=>{
  assert.match(js,/const laneWidth=Math\.round\(windowNode\.getBoundingClientRect\(\)\.width\|\|windowNode\.clientWidth\|\|0\)/);
  assert.match(js,/const signature=text\+'\|'\+laneWidth/);
  assert.match(js,/ticker\.dataset\.s666TickerSignature===signature/);
  assert.match(js,/if\(unchanged&&active\) return/);
  assert.match(js,/ticker\.dataset\.s666TickerSignature=signature/);
  const signatureCheck=js.indexOf("if(unchanged&&active) return");
  const stopCheck=js.indexOf('stopTickerAnimation(ticker);',js.indexOf('function syncTickerMotion'));
  assert.ok(signatureCheck>0&&stopCheck>signatureCheck,'signature guard must run before animation cancellation');
});
test('main reuses the exact shared VELUNA central cyber boot through idempotent bootOnce only',()=>{
  assert.match(centralBoot,/CYBER BOOTING/);
  assert.match(centralBoot,/CONNECTING RADIO CORE/);
  assert.match(centralBoot,/STARTING AUDIO PATH/);
  assert.match(centralBoot,/SYNCHRONIZING SYSTEMS/);
  assert.match(centralBoot,/PLAYER SEQUENCE ARMED/);
  assert.match(centralBoot,/requestAnimationFrame\(tick\)/);
  assert.match(centralBoot,/bootOnce\(\);/);
  assert.match(js,/function ensureVelunaCentralBoot\(\)/);
  assert.match(js,/central\.bootOnce\?\.\(\)/);
  assert.match(js,/S666CentralBootScreen\?\.bootOnce\?\.\(\)/);
  assert.match(js,/\/js\/central-boot-screen\.js\?v=20260812-v200/);
  assert.doesNotMatch(js,/central\.show|S666CentralBootScreen\.show|\.isActive\?\.\(\)/);
  assert.doesNotMatch(js,/installBootAfterCentralOwner/);
  assert.doesNotMatch(js,/s666MainCyberBoot/);
  assert.doesNotMatch(css,/s666-main-cyber-boot/);
  assert.doesNotMatch(js,/START AUDIO|USER GESTURE REQUIRED|play\.click\(\)/);
  assert.doesNotMatch(js,/new AudioContext|webkitAudioContext|createMediaElementSource|fetch\(/);
});
test('DNA wave stays contained while reactor and phase keep strong stage-driven reactivity',()=>{
  assert.match(css,/#pcLeftFxAddon \.pc-addon-waveform\{overflow:hidden!important;align-items:flex-end!important\}/);
  assert.match(css,/#pcLeftFxAddon \.pc-addon-waveform i\{max-height:calc\(100% - 6px\)!important;min-height:7%!important;transform:none!important;transform-origin:bottom!important/);
  assert.match(css,/#pcLeftFxAddon \.pc-addon-reactor-core/);
  assert.match(css,/#pcRightFxAddon \.pc-addon-phase/);
  assert.match(css,/--s666-stage-pulse/);
  assert.match(css,/--s666-stage-peak/);
  assert.match(css,/--s666-stage-mid/);
  assert.doesNotMatch(js,/__MeterBus|MeterBus/);
});
