import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
const js=read('js/main-veluna-adapter.js');
const css=read('css/main-veluna-adapter.css');
const centralBoot=read('js/central-boot-screen.js');
const headers=read('_headers');
const bootstrap=read('config/veluna-assets.js');

test('main VELUNA adapter root/public mirrors are byte-identical',()=>{
  assert.equal(read('public/js/main-veluna-adapter.js'),js);
  assert.equal(read('public/css/main-veluna-adapter.css'),css);
  assert.equal(read('public/_headers'),headers);
});
test('bootstrap config is revalidated and loads one main adapter',()=>{
  assert.match(headers,/\/config\/\*\n  Cache-Control: no-cache, must-revalidate/);
  assert.match(bootstrap,/mainVelunaAdapterVersion = '2026-08-23-main-ticker-dynamic-lane-dna-contained-v4'/);
  assert.match(bootstrap,/main-veluna-adapter\.css/);
  assert.match(bootstrap,/main-veluna-adapter\.js/);
});
test('main ticker uses one measured lane and a deterministic infinite animation driver',()=>{
  assert.match(js,/measureTextWidth\(ticker\)/);
  assert.match(js,/measureSeparatorWidth\(ticker\)/);
  assert.match(js,/shift=Math\.max\(1,itemWidth\+gapPadding\+separatorWidth\)/);
  assert.match(js,/const duration=Math\.max\(12,shift\/42\)/);
  assert.doesNotMatch(js,/Math\.min\(52,shift\/42\)/);
  assert.match(js,/iterations:Infinity/);
  assert.match(js,/ticker\.animate\(/);
  assert.match(js,/tickerAnimation\.id='s666-main-marquee'/);
  assert.match(js,/data-s666-ticker-driver/);
  assert.match(js,/ticker\.classList\.add\('is-running'\)/);
  assert.match(js,/MutationObserver/);
  assert.match(css,/content:" ◆ " attr\(data-s666-marquee-text\)/);
  assert.match(css,/linear infinite!important/);
  assert.match(css,/data-s666-ticker-driver="waapi"/);
  assert.match(css,/data-s666-ticker-driver="css"/);
});
test('main ticker geometry starts after the cover and ends at the History button right edge',()=>{
  assert.match(js,/function syncTickerGeometry\(\)/);
  assert.match(js,/const history=q\('#historyToggle'/);
  assert.match(js,/rect\.right-nowRect\.left\+14/);
  assert.match(js,/nowRect\.right-rect\.right/);
  assert.doesNotMatch(js,/nowRect\.right-rect\.left\+12/);
  assert.match(js,/--s666-main-ticker-left/);
  assert.match(js,/--s666-main-ticker-right/);
  assert.match(js,/--s666-main-ticker-width/);
  assert.match(js,/\['play','playing','pause','loadedmetadata','durationchange'\]/);
  assert.match(css,/width:var\(--s666-main-ticker-width/);
  assert.match(css,/left:var\(--s666-main-ticker-left,14px\)!important/);
  assert.match(css,/#historyToggle\{position:relative!important;z-index:7!important\}/);
  assert.match(css,/\.ticker-window\{[\s\S]*overflow:hidden!important;[\s\S]*isolation:isolate!important/);
});
test('main ticker is absolutely anchored in the lower third with breathing room below',()=>{
  assert.match(css,/position:absolute!important/);
  assert.match(css,/top:auto!important/);
  assert.match(css,/bottom:42px!important/);
  assert.match(css,/min-height:44px!important/);
  assert.match(css,/height:44px!important/);
  assert.match(css,/margin:0!important/);
  assert.match(css,/align-self:auto!important/);
  assert.match(css,/display:flex!important/);
  assert.match(css,/align-items:center!important/);
  assert.match(css,/line-height:34px!important/);
  assert.doesNotMatch(css,/grid-template-rows:minmax\(0,1fr\) 62px!important/);
  assert.doesNotMatch(css,/bottom:16px!important/);
});
test('unchanged repeated metadata does not restart a long-title marquee before a full cycle',()=>{
  assert.match(js,/const laneWidth=Math\.round\(windowNode\.getBoundingClientRect\(\)\.width\|\|windowNode\.clientWidth\|\|0\)/);
  assert.match(js,/const signature=text\+'\|'\+laneWidth/);
  assert.match(js,/ticker\.dataset\.s666TickerSignature===signature/);
  assert.match(js,/if\(unchanged&&active\) return/);
  assert.match(js,/ticker\.dataset\.s666TickerSignature=signature/);
  const signatureCheck=js.indexOf("if(unchanged&&active) return");
  const stopCheck=js.indexOf('stopTickerAnimation(ticker);',js.indexOf('function syncTickerMotion'));
  assert.ok(signatureCheck>0&&stopCheck>signatureCheck,'signature guard must run before animation cancellation');
});
test('main reuses the exact shared VELUNA central cyber boot through idempotent bootOnce only',()=>{
  assert.match(centralBoot,/CYBER BOOTING/);
  assert.match(centralBoot,/CONNECTING RADIO CORE/);
  assert.match(centralBoot,/STARTING AUDIO PATH/);
  assert.match(centralBoot,/SYNCHRONIZING SYSTEMS/);
  assert.match(centralBoot,/PLAYER SEQUENCE ARMED/);
  assert.match(centralBoot,/requestAnimationFrame\(tick\)/);
  assert.match(centralBoot,/bootOnce\(\);/);
  assert.match(js,/function ensureVelunaCentralBoot\(\)/);
  assert.match(js,/central\.bootOnce\?\.\(\)/);
  assert.match(js,/S666CentralBootScreen\?\.bootOnce\?\.\(\)/);
  assert.match(js,/\/js\/central-boot-screen\.js\?v=20260812-v200/);
  assert.doesNotMatch(js,/central\.show|S666CentralBootScreen\.show|\.isActive\?\.\(\)/);
  assert.doesNotMatch(js,/installBootAfterCentralOwner/);
  assert.doesNotMatch(js,/s666MainCyberBoot/);
  assert.doesNotMatch(css,/s666-main-cyber-boot/);
  assert.doesNotMatch(js,/START AUDIO|USER GESTURE REQUIRED|play\.click\(\)/);
  assert.doesNotMatch(js,/new AudioContext|webkitAudioContext|createMediaElementSource|fetch\(/);
});
test('DNA wave stays contained while reactor and phase keep strong stage-driven reactivity',()=>{
  assert.match(css,/#pcLeftFxAddon \.pc-addon-waveform\{overflow:hidden!important;align-items:flex-end!important\}/);
  assert.match(css,/#pcLeftFxAddon \.pc-addon-waveform i\{max-height:calc\(100% - 6px\)!important;min-height:7%!important;transform:none!important;transform-origin:bottom!important/);
  assert.match(css,/#pcLeftFxAddon \.pc-addon-reactor-core/);
  assert.match(css,/#pcRightFxAddon \.pc-addon-phase/);
  assert.match(css,/--s666-stage-pulse/);
  assert.match(css,/--s666-stage-peak/);
  assert.match(css,/--s666-stage-mid/);
  assert.doesNotMatch(js,/__MeterBus|MeterBus/);
});