services:
  - type: web
    name: auto-setup-render-for-backend-mp3
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MASTER_ADMIN_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MASTERING_BACKEND_TOKEN
        sync: false
      - key: MASTERING_BACKEND_URL
        value: https://auto-setup-render-for-backend-mp3.onrender.com
      - key: MASTERING_WORKER_URL
        value: https://666soundsdesign-mp3-mastering.fraggelpower666.workers.dev
      - key: SYSTEM_PW_WORKER_URL
        value: https://system-pw-worker.fraggelpower666.workers.dev
