name: Mirror Backup

on:
  push:
    branches:
      - WebRadio-666SOUNDsDESIGn

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: WebRadio-666SOUNDsDESIGn

      - name: Push to backup branch in same repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git checkout -B 666BackupMirror
          git push origin 666BackupMirror --force
