name: Mirror Backup

on:
  push:
    branches:
      - BACKUPMIRROR   # <- WICHTIG

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/xfraggelpower666x/WebRadio-666SOUNDsDESIGn-Backup-Mirror.git

          git push mirror HEAD:main --force
